defmodule Loop.Patterns do
  @moduledoc false

  alias Loop.Patterns.{Advanced, Collection, Core, Helpers, Reduce, Search, Transform}

  # Ordered matcher table: earlier entries win. Core/Search/Reduce/Transform
  # matchers take (initials, body); Advanced/Collection additionally receive
  # the shared helper callbacks.
  @table [
    {Core, :map_pattern},
    {Core, :map_append_pattern},
    {Core, :filter_pattern},
    {Core, :filter_append_pattern},
    {Core, :reject_pattern},
    {Core, :reject_append_pattern},
    {Core, :reverse_pattern},
    {Core, :filter_map_pattern},
    {Advanced, :concat_pattern},
    {Advanced, :concat_two_pattern},
    {Advanced, :flat_map_pattern},
    {Advanced, :map_reduce_append_pattern},
    {Advanced, :map_reduce_pattern},
    {Advanced, :flat_map_reduce_prepend_pattern},
    {Advanced, :flat_map_reduce_pattern},
    {Core, :all_early_break_pattern},
    {Core, :none_pattern},
    {Search, :find_pattern},
    {Search, :find_default_pattern},
    {Search, :find_value_pattern},
    {Search, :find_value_default_pattern},
    {Search, :member_pattern},
    {Core, :any_early_break_pattern},
    {Search, :find_at_default_offset_pattern},
    {Search, :find_at_offset_pattern},
    {Search, :find_at_default_pattern},
    {Search, :find_at_pattern},
    {Search, :find_index_pattern},
    {Search, :find_index_offset_pattern},
    {Search, :fetch_pattern},
    {Core, :count_pattern},
    {Advanced, :count_until_pattern},
    {Advanced, :index_aware_map_pattern},
    {Advanced, :index_aware_filter_pattern},
    {Advanced, :index_aware_each_pattern},
    {Advanced, :sum_by_pattern},
    {Advanced, :product_by_pattern},
    {Advanced, :average_pattern},
    {Advanced, :delete_at_pattern},
    {Advanced, :list_delete_at_tail_pattern},
    {Advanced, :list_update_at_pattern},
    {Advanced, :list_insert_at_pattern},
    {Advanced, :map_into_pattern},
    {Core, :length_pattern},
    {Core, :any_pattern},
    {Core, :all_pattern},
    {Core, :each_pattern},
    {Core, :take_while_pattern},
    {Core, :take_while_append_pattern},
    {Core, :map_while_pattern},
    {Core, :drop_while_pattern},
    {Collection, :partition_pattern},
    {Advanced, :chunk_every_pattern},
    {Advanced, :chunk_by_pattern},
    {Advanced, :chunk_while_pattern},
    {Collection, :take_pattern},
    {Advanced, :slice_pattern},
    {Advanced, :map_intersperse_pattern},
    {Advanced, :map_join_pattern},
    {Advanced, :map_every_pattern},
    {Advanced, :take_every_pattern},
    {Advanced, :drop_every_pattern},
    {Collection, :drop_pattern},
    {Collection, :split_while_pattern},
    {Collection, :split_while_append_pattern},
    {Collection, :split_pattern},
    {Advanced, :split_count_up_pattern},
    {Transform, :with_index_pattern},
    {Advanced, :zip_with_nary_pattern},
    {Advanced, :zip_reduce_nary_pattern},
    {Advanced, :zip_nary_pattern},
    {Advanced, :zip_with_pattern},
    {Advanced, :zip_reduce_pattern},
    {Transform, :zip_pattern},
    {Advanced, :sliding_window_reduce_pattern},
    {Advanced, :adjacent_pairs_pattern},
    {Advanced, :adjacent_pairs_map_pattern},
    {Advanced, :unzip_pattern},
    {Reduce, :reduce_while_pattern},
    {Transform, :dedup_pattern},
    {Advanced, :dedup_by_pattern},
    {Transform, :dedup_first_flag_pattern},
    {Advanced, :uniq_pattern},
    {Advanced, :uniq_by_pattern},
    {Advanced, :min_max_by_pattern},
    {Advanced, :max_by_min_by_pattern},
    {Advanced, :min_max_pattern},
    {Reduce, :max_min_pattern},
    {Transform, :frequencies_pattern},
    {Advanced, :frequencies_by_pattern},
    {Advanced, :frequencies_get_put_pattern},
    {Advanced, :group_by_pattern},
    {Advanced, :group_by_get_put_pattern},
    {Transform, :map_new_pattern},
    {Advanced, :map_put_new_pattern},
    {Advanced, :map_update_pattern},
    {Advanced, :map_merge_pattern},
    {Transform, :into_mapset_pattern},
    {Reduce, :scan_tuple_pattern},
    {Reduce, :scan_pattern},
    {Reduce, :reduce_tuple_pattern},
    {Reduce, :reduce_constant_pattern},
    {Reduce, :while_multi_pattern},
    {Reduce, :filter_count_pattern},
    {Search, :any_with_index_pattern},
    {Advanced, :range_down_pattern},
    {Reduce, :reduce_pattern}
  ]

  def try_all(initials, body) do
    callbacks = Helpers.standard_callbacks()

    Enum.find_value(@table, fn
      {mod, fun} when mod in [Advanced, Collection] ->
        apply(mod, fun, [initials, body, callbacks])

      {mod, fun} ->
        apply(mod, fun, [initials, body])
    end)
  end
end
